name: Juicy Shop Workflow
run-name: ${{ github.actor }} is running some SAST out on GitHub Actions 🚀
on: [push]

jobs:
  test:
    name: "SAST Test"  
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        # working-directory: ./juice-shop

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

# # Cache yarn dependencies
#       - name: Cache yarn dependencies
#         uses: actions/cache@v3
#         with:
#          path: |
#           node_modules
#           yarn.lock
#           .yarn
#          key: yarn-cache-${{ hashFiles('yarn.lock') }}  # Cache key based on yarn.lock
#          restore-keys: |
#            yarn-cache-

#      # Check if node_modules exist after restoring cache
#       - name: Verify cached dependencies
#         run: |
#           if [ ! -d "node_modules" ]; then
#             echo "node_modules not found, installing dependencies..."
#             yarn install
#           else
#             echo "Using cached node_modules"
#           fi
      - name: Set up Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'

    # Install dependencies
      - name: Install dependencies
        run: yarn install

     # Run tests using cached dependencies
      - name: Run yarn tests
        run: |
          yarn test
        continue-on-error: true  # Past if tests fail


      - name: set up gitleaks for the runner
        uses: gitleaks/gitleaks-action@v2
        continue-on-error: true
        with:
          config: ""
          fail_on_secrets: true

    
        
        

    #   - name: Install dependencies
    #     run: |