name: Juicy Shop Workflow
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]

jobs:
  test:
    name: "SAST Test"  
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./juice-shop

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: gitleaks
        uses: gitleaks/gitleaks-action@v2
        run: gitleaks detect --verbose --source . -f json -r gitleaks.json

    #   - name: Install dependencies
    #     run: |